name: WSL Runner Test
on:
  push:
    paths:
      - 'terraform/main.tf'
      - 'app/**'

jobs:
  hello-wsl:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: |
          echo "Hello Jin! GitHub Actions is successfully running on your WSL."
          hostname
          date

      - name: Check Terraform
        run: terraform --version
